spring:
  application:
    name: desafiovagaitau
properties:
  time-window: 60
server:
  error:
    include-stacktrace: never
logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health